name: Release

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    needs: [quality]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install
      - run: yarn semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
